### ISSUE TITLE
`fortls` could not be spawned when opening atom with a default file

### ISSUE THREAD

**Issue by william-dawson** [hansec/ide-fortran#7] opened 2018-06-08 02:33 UTC
IDE-Fortran developers,

I have run into a minor bug. If I open up a project with atom, and there is no default source file, everything works great. But let's say I open up from my project file x.f90. Then I close atom. When I reopen that project with atom, x.f90 will be shown in a tab by default. However, in this situation I get a bug `'fortls' could not be spawned`. See the picture below. In this case, IDE-Fortran does not work. However, if I close that default source file, close atom, and reopen atom (now with no default source file), it works fine. 

My configuration:
macOS 10.13.4
Atom 1.27.2
ide-fortran 0.1.9
fortran-language-server 0.5.0

Let me know if there is any other debug information I can provide.

![error_report](https://user-images.githubusercontent.com/19283177/41135703-ca17582c-6b0d-11e8-8a4b-52034059e81b.png)

**Comment by hansec** [comment] 2018-06-08 15:12
Hmmm, this is odd. I have the same configuration you have but I have never seen this issue. The only thing I can think of that might cause this is some sort of race condition where the system path is not being set fully before Atom tries to launch `fortls` for the first time. Can you try setting the path to `fortls` explicitly in settings and see if that resolves things? Thanks for the report.

**Comment by william-dawson** [comment] 2018-06-12 01:05
Thanks a bunch, that fixed the problem!

**Comment by hansec** [comment] 2018-06-14 00:22
Great! I am going to go ahead and close this issue. I will comment here if I am able to track down what might be causing this. Although, I suspect the issue is in an upstream package since it appears to be path related.

**Closed as completed by hansec** 2018-06-14 00:22 UTC

**Comment by xavierquinn** [comment] 2020-01-25 16:05
"Can you try setting the path to fortls explicitly in settings and see if that resolves things?"

What is the usual location for fortls on MacOS X?
